### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by eca21a-2018112021** [eca21x/HelpDesk#138]
org: eca21x

repo: eca21a-00-00-20-eca21a-2018112021
url: https://github.com/eca21x/eca21a-00-00-20-eca21a-2018112021

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-20-eca21a-2018112021
Processing request above
https://github.com/eca21x/eca21a-00-00-20-eca21a-2018112021

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-20-eca21a-2018112021
Success! Start your engine!
https://github.com/eca21x/eca21a-00-00-20-eca21a-2018112021
