### ISSUE TITLE
활성화바랍니다.

### ISSUE THREAD

**Issue by 2020114011-cpf21a** [eca21x/HelpDesk#201]
org:eca21x
repo:eca21a-00-00-40-2020114011-cpf21a

https://github.com/eca21x/eca21a-00-00-40-2020114011-cpf21a

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/eca21x/eca21a-00-00-40-2020114011-cpf21a
