### ISSUE TITLE
활성화바랍니다

### ISSUE THREAD

**Issue by wls2186** [eca21x/HelpDesk#208]
org: eca21a

repo: eca21a-nmisp-wls2186

url: https://github.com/eca21a/eca21a-nmisp-wls2186

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21a (expecting eca21x)

**Comment by kangwonlee** [comment]
org: eca21x

repo: eca21a-nmisp-wls2186

url: https://github.com/eca21a/eca21a-nmisp-wls2186

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/eca21x/eca21a-nmisp-wls2186

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Org your_org_here seems out of scope

**Comment by kangwonlee** [comment]
@wls2186 nmisp 저장소는 활성화 대상이 아닙니다
