### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by jongmin-eca20c** [eca21x/HelpDesk#380]
org: eca21x

repo: eca21a-00-00-03-jongmin-eca20c

url: https://github.com/eca21x/eca21a-00-00-30-jongmin-eca20c

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/eca21x/eca21a-00-00-03-jongmin-eca20c

**Comment by jongmin-eca20c** [comment]
org: eca21x
repo: eca21a-00-00-03-jongmin-eca20c
url: https://github.com/eca21x/eca21a-00-00-30-jongmin-eca20c

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/eca21x/eca21a-00-00-03-jongmin-eca20c

**Comment by kangwonlee** [comment]
org: eca21x
repo: eca21a-00-00-30-jongmin-eca20c
url: https://github.com/eca21x/eca21a-00-00-30-jongmin-eca20c

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-30-jongmin-eca20c
Processing request above
https://github.com/eca21x/eca21a-00-00-30-jongmin-eca20c

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-30-jongmin-eca20c
Success! Start your engine!
https://github.com/eca21x/eca21a-00-00-30-jongmin-eca20c
