### ISSUE TITLE
Activate please

### ISSUE THREAD

**Issue by kangwonlee** [eca21x/HelpDesk#49]
org: eca21x
repo: eca21a-00-00-10-eca21a-nmisp-bangjunsik

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-eca21a-nmisp-bangjunsik
Processing request above

**Comment by kangwon-naver** [comment]
org: eca21x
repo: eca21a-00-00-10-eca21a-nmisp-bangjunsik
Success! Start your engine!
